# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eb55c824b2d79bf908b43925928917d1c398b7f1c32d68244d3d70ccfa6608958d2c4fefe443325da08068da816d452fc70d9c0ca7a662b39805f23ed21bdb0
  STEAM_WEB_API_KEY: <%= ENV["STEAM_WEB_API_KEY"]%>

test:
  secret_key_base: ced12bb71da27acc5e88a8ff82d7a114286ee5efd6d14eedfdc0c1ef0aac481d39bdbd166036ead10b6dddbf9b4725cdfa73d585659fc1ebff26db52405e5fe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  STEAM_WEB_API_KEY: <%= ENV["STEAM_WEB_API_KEY"]%>
  
